name: Deploy Flask API to EC2

on:
  push:
    branches:
      - main # Deploy changes in main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: Production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t flask-api:latest .
          docker tag flask-api:latest ${{ secrets.DOCKER_USERNAME }}/flask-api:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/flask-api:latest

      - name: SSH into EC2 and deploy container
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/flask-api:latest
            docker stop $(docker ps -q) || true  # Detiene cualquier contenedor en ejecución
            docker run -d -p 8080:5000 ${{ secrets.DOCKER_USERNAME }}/flask-api:latest
